// src/utils/phonePrefixes.js

export function getPhonePrefixes() {
  return [
    { dial_code: '+1', country: 'Estados Unidos', emoji: '🇺🇸' },
    { dial_code: '+1', country: 'Canadá', emoji: '🇨🇦' },
    { dial_code: '+52', country: 'México', emoji: '🇲🇽' },
    { dial_code: '+53', country: 'Cuba', emoji: '🇨🇺' },
    { dial_code: '+54', country: 'Argentina', emoji: '🇦🇷' },
    { dial_code: '+55', country: 'Brasil', emoji: '🇧🇷' },
    { dial_code: '+56', country: 'Chile', emoji: '🇨🇱' },
    { dial_code: '+57', country: 'Colombia', emoji: '🇨🇴' },
    { dial_code: '+58', country: 'Venezuela', emoji: '🇻🇪' },
    { dial_code: '+51', country: 'Perú', emoji: '🇵🇪' },
    { dial_code: '+502', country: 'Guatemala', emoji: '🇬🇹' },
    { dial_code: '+503', country: 'El Salvador', emoji: '🇸🇻' },
    { dial_code: '+504', country: 'Honduras', emoji: '🇭🇳' },
    { dial_code: '+505', country: 'Nicaragua', emoji: '🇳🇮' },
    { dial_code: '+506', country: 'Costa Rica', emoji: '🇨🇷' },
    { dial_code: '+507', country: 'Panamá', emoji: '🇵🇦' },
    { dial_code: '+598', country: 'Uruguay', emoji: '🇺🇾' },
    { dial_code: '+591', country: 'Bolivia', emoji: '🇧🇴' },
    { dial_code: '+569', country: 'Chile (Móvil)', emoji: '🇨🇱' },
    { dial_code: '+44', country: 'Reino Unido', emoji: '🇬🇧' },
    { dial_code: '+34', country: 'España', emoji: '🇪🇸' },
    { dial_code: '+33', country: 'Francia', emoji: '🇫🇷' },
    { dial_code: '+49', country: 'Alemania', emoji: '🇩🇪' },
    { dial_code: '+39', country: 'Italia', emoji: '🇮🇹' },
    { dial_code: '+7', country: 'Rusia', emoji: '🇷🇺' },
    { dial_code: '+81', country: 'Japón', emoji: '🇯🇵' },
    { dial_code: '+82', country: 'Corea del Sur', emoji: '🇰🇷' },
    { dial_code: '+61', country: 'Australia', emoji: '🇦🇺' },
    { dial_code: '+64', country: 'Nueva Zelanda', emoji: '🇳🇿' },
    { dial_code: '+91', country: 'India', emoji: '🇮🇳' },
    { dial_code: '+62', country: 'Indonesia', emoji: '🇮🇩' },
    { dial_code: '+63', country: 'Filipinas', emoji: '🇵🇭' },
    { dial_code: '+65', country: 'Singapur', emoji: '🇸🇬' },
    { dial_code: '+66', country: 'Tailandia', emoji: '🇹🇭' },
    { dial_code: '+86', country: 'China', emoji: '🇨🇳' },
    { dial_code: '+90', country: 'Turquía', emoji: '🇹🇷' },
    { dial_code: '+234', country: 'Nigeria', emoji: '🇳🇬' },
    { dial_code: '+27', country: 'Sudáfrica', emoji: '🇿🇦' },
    { dial_code: '+254', country: 'Kenia', emoji: '🇰🇪' },
    { dial_code: '+20', country: 'Egipto', emoji: '🇪🇬' },
  ];
}